name: Check version

on: workflow_call

jobs:
  main-job:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-vcheck
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Build
        shell: pwsh
        run: .\version-check.ps1
