name: Automated Checks (pull request)

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, edited, synchronize]

jobs:
  lint:
    uses: ./.github/workflows/action_check-lint.yml
  
  unit-tests:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-test
      cancel-in-progress: true

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: npm install
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:mocha:prod
  
  ensure-new-version:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-version
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Ensure newer version that last release
        shell: pwsh
        run: .\version-check.ps1