name: Debug test

on:
  workflow_dispatch

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-publish
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm run rebuild:release

      - name: Prepare output for publishing
        shell: pwsh
        run: .\prepare-output.ps1

      - run: |
          cd ./dist
          ls